export const SEARCH_NOTE_START = 'SEARCH_NOTE_START';
export const SEARCH_NOTE_RESULTS = 'SEARCH_NOTE_RESULTS';
export const SEARCH_NOTE_ERROR = 'SEARCH_NOTE_ERROR';

export const FETCH_NOTE_START = 'FETCH_NOTE_START';
export const FETCH_NOTE_RESULTS = 'FETCH_NOTE_RESULTS';
export const FETCH_NOTE_ERROR = 'FETCH_NOTE_ERROR';
export const FETCH_NOTE_NEW_PAGE = 'FETCH_NOTE_NEW_PAGE';
export const FETCH_NOTE_NEW_LIMIT = 'FETCH_NOTE_NEW_LIMIT';

export const SINGLE_NOTE_START = 'SINGLE_NOTE_START';
export const SINGLE_NOTE_RESULTS = 'SINGLE_NOTE_RESULTS';
export const SINGLE_NOTE_ERROR = 'SINGLE_NOTE_ERROR';

export const SAVE_NOTE_START = 'SAVE_NOTE_START';
export const SAVE_NOTE_SUCCESS = 'SAVE_NOTE_SUCCESS';
export const SAVE_NOTE_ERROR = 'SAVE_NOTE_ERROR';

export const DELETE_NOTE_START = 'DELETE_NOTE_START';
export const DELETE_NOTE_SUCCESS = 'DELETE_NOTE_SUCCESS';
export const DELETE_NOTE_ERROR = 'DELETE_NOTE_ERROR';
