export const FETCH_TASK_START = 'FETCH_TASK_START';
export const FETCH_TASK_RESULTS = 'FETCH_TASK_RESULTS';
export const FETCH_TASK_ERROR = 'FETCH_TASK_ERROR';
export const FETCH_TASK_NEW_PAGE = 'FETCH_TASK_NEW_PAGE';
