export const SEARCH_PARTNER_COMPANY_START = 'SEARCH_PARTNER_COMPANY_START';
export const SEARCH_PARTNER_COMPANY_RESULTS = 'SEARCH_PARTNER_COMPANY_RESULTS';
export const SEARCH_PARTNER_COMPANY_ERROR = 'SEARCH_PARTNER_COMPANY_ERROR';

export const FETCH_PARTNER_COMPANY_START = 'FETCH_PARTNER_COMPANY_START';
export const FETCH_PARTNER_COMPANY_RESULTS = 'FETCH_PARTNER_COMPANY_RESULTS';
export const FETCH_PARTNER_COMPANY_ERROR = 'FETCH_PARTNER_COMPANY_ERROR';
export const FETCH_PARTNER_COMPANY_NEW_PAGE = 'FETCH_PARTNER_COMPANY_NEW_PAGE';

export const SINGLE_PARTNER_COMPANY_START = 'SINGLE_PARTNER_COMPANY_START';
export const SINGLE_PARTNER_COMPANY_RESULTS = 'SINGLE_PARTNER_COMPANY_RESULTS';
export const SINGLE_PARTNER_COMPANY_ERROR = 'SINGLE_PARTNER_COMPANY_ERROR';

export const SAVE_PARTNER_COMPANY_START = 'SAVE_PARTNER_COMPANY_START';
export const SAVE_PARTNER_COMPANY_SUCCESS = 'SAVE_PARTNER_COMPANY_SUCCESS';
export const SAVE_PARTNER_COMPANY_ERROR = 'SAVE_PARTNER_COMPANY_ERROR';

export const DELETE_PARTNER_COMPANY_START = 'DELETE_PARTNER_COMPANY_START';
export const DELETE_PARTNER_COMPANY_SUCCESS = 'DELETE_PARTNER_COMPANY_SUCCESS';
export const DELETE_PARTNER_COMPANY_ERROR = 'DELETE_PARTNER_COMPANY_ERROR';
