export const RESET_HOLD_SERVICE_DATA = 'RESET_HOLD_SERVICE_DATA';

export const SEARCH_HOLD_SERVICE_START = 'SEARCH_HOLD_SERVICE_START';

export const FETCH_HOLD_SERVICE_START = 'FETCH_HOLD_SERVICE_START';
export const FETCH_HOLD_SERVICE_SUCCESS = 'FETCH_HOLD_SERVICE_SUCCESS';
export const FETCH_HOLD_SERVICE_ERROR = 'FETCH_HOLD_SERVICE_ERROR';
export const FETCH_HOLD_SERVICE_NEW_PAGE = 'FETCH_HOLD_SERVICE_NEW_PAGE';
