export const FETCH_STATISTICS_START = 'FETCH_STATISTICS_START';
export const FETCH_STATISTICS_RESULTS = 'FETCH_STATISTICS_RESULTS';
export const FETCH_STATISTICS_ERROR = 'FETCH_STATISTICS_ERROR';
export const FETCH_STATISTICS_NEW_PAGE = 'FETCH_STATISTICS_NEW_PAGE';
