export const RESET_LIEN_DATA = 'RESET_LIEN_DATA';

export const SEARCH_LIEN_START = 'SEARCH_LIEN_START';

export const FETCH_LIEN_START = 'FETCH_LIEN_START';
export const FETCH_LIEN_SUCCESS = 'FETCH_LIEN_SUCCESS';
export const FETCH_LIEN_ERROR = 'FETCH_LIEN_ERROR';
export const FETCH_LIEN_NEW_PAGE = 'FETCH_LIEN_NEW_PAGE';

export const SINGLE_LIEN_START = 'SINGLE_LIEN_START';
export const SINGLE_LIEN_SUCCESS = 'SINGLE_LIEN_SUCCESS';
export const SINGLE_LIEN_ERROR = 'SINGLE_LIEN_ERROR';

export const SAVE_LIEN_START = 'SAVE_LIEN_START';
export const SAVE_LIEN_SUCCESS = 'SAVE_LIEN_SUCCESS';
export const SAVE_LIEN_ERROR = 'SAVE_LIEN_ERROR';

export const DELETE_LIEN_START = 'DELETE_LIEN_START';
export const DELETE_LIEN_SUCCESS = 'DELETE_LIEN_SUCCESS';
export const DELETE_LIEN_ERROR = 'DELETE_LIEN_ERROR';

export const STATISTICS_LIEN_START = 'STATISTICS_LIEN_START';
export const STATISTICS_LIEN_SUCCESS = 'STATISTICS_LIEN_SUCCESS';
export const STATISTICS_LIEN_ERROR = 'STATISTICS_LIEN_ERROR';
