export const FETCH_NOTIFICATIONS_START = 'FETCH_NOTIFICATIONS_START';
export const FETCH_NOTIFICATIONS_RESULTS = 'FETCH_NOTIFICATIONS_RESULTS';
export const FETCH_NOTIFICATIONS_ERROR = 'FETCH_NOTIFICATIONS_ERROR';
export const FETCH_NOTIFICATIONS_NEW_PAGE = 'FETCH_NOTIFICATIONS_NEW_PAGE';
