export const SEARCH_PERSON_EVENTS_START = 'SEARCH_PERSON_EVENTS_START';
export const SEARCH_PERSON_EVENTS_RESULTS = 'SEARCH_PERSON_EVENTS_RESULTS';
export const SEARCH_PERSON_EVENTS_ERROR = 'SEARCH_PERSON_EVENTS_ERROR';

export const FETCH_PERSON_EVENTS_START = 'FETCH_PERSON_EVENTS_START';
export const FETCH_PERSON_EVENTS_RESULTS = 'FETCH_PERSON_EVENTS_RESULTS';
export const FETCH_PERSON_EVENTS_ERROR = 'FETCH_PERSON_EVENTS_ERROR';
export const FETCH_PERSON_EVENTS_NEW_PAGE = 'FETCH_PERSON_EVENTS_NEW_PAGE';

export const SINGLE_PERSON_EVENTS_START = 'SINGLE_PERSON_EVENTS_START';
export const SINGLE_PERSON_EVENTS_RESULTS = 'SINGLE_PERSON_EVENTS_RESULTS';
export const SINGLE_PERSON_EVENTS_ERROR = 'SINGLE_PERSON_EVENTS_ERROR';

export const SAVE_PERSON_EVENTS_START = 'SAVE_PERSON_EVENTS_START';
export const SAVE_PERSON_EVENTS_SUCCESS = 'SAVE_PERSON_EVENTS_SUCCESS';
export const SAVE_PERSON_EVENTS_ERROR = 'SAVE_PERSON_EVENTS_ERROR';

export const DELETE_PERSON_EVENTS_START = 'DELETE_PERSON_EVENTS_START';
export const DELETE_PERSON_EVENTS_SUCCESS = 'DELETE_PERSON_EVENTS_SUCCESS';
export const DELETE_PERSON_EVENTS_ERROR = 'DELETE_PERSON_EVENTS_ERROR';
