export const SEARCH_JUDGE_START = 'SEARCH_JUDGE_START';
export const SEARCH_JUDGE_RESULTS = 'SEARCH_JUDGE_RESULTS';
export const SEARCH_JUDGE_ERROR = 'SEARCH_JUDGE_ERROR';

export const FETCH_JUDGE_START = 'FETCH_JUDGE_START';
export const FETCH_JUDGE_RESULTS = 'FETCH_JUDGE_RESULTS';
export const FETCH_JUDGE_ERROR = 'FETCH_JUDGE_ERROR';
export const FETCH_JUDGE_NEW_PAGE = 'FETCH_JUDGE_NEW_PAGE';

export const SINGLE_JUDGE_START = 'SINGLE_JUDGE_START';
export const SINGLE_JUDGE_RESULTS = 'SINGLE_JUDGE_RESULTS';
export const SINGLE_JUDGE_ERROR = 'SINGLE_JUDGE_ERROR';

export const SAVE_JUDGE_START = 'SAVE_JUDGE_START';
export const SAVE_JUDGE_SUCCESS = 'SAVE_JUDGE_SUCCESS';
export const SAVE_JUDGE_ERROR = 'SAVE_JUDGE_ERROR';

export const DELETE_JUDGE_START = 'DELETE_JUDGE_START';
export const DELETE_JUDGE_SUCCESS = 'DELETE_JUDGE_SUCCESS';
export const DELETE_JUDGE_ERROR = 'DELETE_JUDGE_ERROR';
