export const SEARCH_VENUE_START = 'SEARCH_VENUE_START';
export const SEARCH_VENUE_RESULTS = 'SEARCH_VENUE_RESULTS';
export const SEARCH_VENUE_ERROR = 'SEARCH_VENUE_ERROR';

export const FETCH_VENUE_START = 'FETCH_VENUE_START';
export const FETCH_VENUE_RESULTS = 'FETCH_VENUE_RESULTS';
export const FETCH_VENUE_ERROR = 'FETCH_VENUE_ERROR';
export const FETCH_VENUE_NEW_PAGE = 'FETCH_VENUE_NEW_PAGE';

export const SINGLE_VENUE_START = 'SINGLE_VENUE_START';
export const SINGLE_VENUE_RESULTS = 'SINGLE_VENUE_RESULTS';
export const SINGLE_VENUE_ERROR = 'SINGLE_VENUE_ERROR';

export const SAVE_VENUE_START = 'SAVE_VENUE_START';
export const SAVE_VENUE_SUCCESS = 'SAVE_VENUE_SUCCESS';
export const SAVE_VENUE_ERROR = 'SAVE_VENUE_ERROR';

export const DELETE_VENUE_START = 'DELETE_VENUE_START';
export const DELETE_VENUE_SUCCESS = 'DELETE_VENUE_SUCCESS';
export const DELETE_VENUE_ERROR = 'DELETE_VENUE_ERROR';
