export const FETCH_SINGLE_JUDGE_START = 'FETCH_SINGLE_JUDGE_START';
export const FETCH_SINGLE_JUDGE_ERROR = 'FETCH_SINGLE_JUDGE_ERROR';
export const FETCH_SINGLE_JUDGE_SUCCESS = 'FETCH_SINGLE_JUDGE_SUCCESS';
export const JUDGE_OVERVIEW_START = 'JUDGE_OVERVIEW_START';
export const JUDGE_OVERVIEW_ERROR = 'JUDGE_OVERVIEW_ERROR';
export const JUDGE_OVERVIEW_SUCCESS = 'JUDGE_OVERVIEW_SUCCESS';
