export const FETCH_LIENS_START = 'FETCH_LIENS_START';
export const FETCH_LIENS_RESULT = 'FETCH_LIENS_RESULT';
export const FETCH_LIENS_ERROR = 'FETCH_LIENS_ERROR';

export const EDIT_LIENS_START = 'EDIT_LIENS_START';
export const EDIT_LIENS_RESULT = 'EDIT_LIENS_RESULT';
export const EDIT_LIENS_ERROR = 'EDIT_LIENS_ERROR';
