export const SEARCH_CALENDAR_WIDGET_START = 'SEARCH_CALENDAR_WIDGET_START';
export const SEARCH_CALENDAR_WIDGET_RESULTS = 'SEARCH_CALENDAR_WIDGET_RESULTS';
export const SEARCH_CALENDAR_WIDGET_ERROR = 'SEARCH_CALENDAR_WIDGET_ERROR';

export const FETCH_CALENDAR_WIDGET_START = 'FETCH_CALENDAR_WIDGET_START';
export const FETCH_CALENDAR_WIDGET_RESULTS = 'FETCH_CALENDAR_WIDGET_RESULTS';
export const FETCH_CALENDAR_WIDGET_ERROR = 'FETCH_CALENDAR_WIDGET_ERROR';
export const FETCH_CALENDAR_WIDGET_NEW_PAGE = 'FETCH_CALENDAR_WIDGET_NEW_PAGE';
