export const FETCH_CASE_METRICS_START = 'FETCH_CASE_METRICS_START';
export const FETCH_CASE_METRICS_ERROR = 'FETCH_CASE_METRICS_ERROR';
export const FETCH_CASE_METRICS_SUCCESS = 'FETCH_CASE_METRICS_SUCCESS';
