export const FETCH_CONTACT_METRICS_START = 'FETCH_CONTACT_METRICS_START';
export const FETCH_CONTACT_METRICS_ERROR = 'FETCH_CONTACT_METRICS_ERROR';
export const FETCH_CONTACT_METRICS_SUCCESS = 'FETCH_CONTACT_METRICS_SUCCESS';
