export const FETCH_SINGLE_CONTACT_START = 'FETCH_SINGLE_CONTACT_START';
export const FETCH_SINGLE_CONTACT_ERROR = 'FETCH_SINGLE_CONTACT_ERROR';
export const FETCH_SINGLE_CONTACT_SUCCESS = 'FETCH_SINGLE_CONTACT_SUCCESS';
export const CONTACT_OVERVIEW_START = 'CONTACT_OVERVIEW_START';
export const CONTACT_OVERVIEW_ERROR = 'CONTACT_OVERVIEW_ERROR';
export const CONTACT_OVERVIEW_SUCCESS = 'CONTACT_OVERVIEW_SUCCESS';
