export const SINGLE_CONTACT_FORM_TYPE_CHANGE = 'SINGLE_CONTACT_FORM_TYPE_CHANGE';

export const SEARCH_CONTACT_START = 'SEARCH_CONTACT_START';
export const SEARCH_CONTACT_RESULTS = 'SEARCH_CONTACT_RESULTS';
export const SEARCH_CONTACT_ERROR = 'SEARCH_CONTACT_ERROR';

export const FETCH_CONTACT_START = 'FETCH_CONTACT_START';
export const FETCH_CONTACT_RESULTS = 'FETCH_CONTACT_RESULTS';
export const FETCH_CONTACT_ERROR = 'FETCH_CONTACT_ERROR';
export const FETCH_CONTACT_NEW_PAGE = 'FETCH_CONTACT_NEW_PAGE';

export const SINGLE_CONTACT_START = 'SINGLE_CONTACT_START';
export const SINGLE_CONTACT_RESULTS = 'SINGLE_CONTACT_RESULTS';
export const SINGLE_CONTACT_ERROR = 'SINGLE_CONTACT_ERROR';

export const SAVE_CONTACT_START = 'SAVE_CONTACT_START';
export const SAVE_CONTACT_SUCCESS = 'SAVE_CONTACT_SUCCESS';
export const SAVE_CONTACT_ERROR = 'SAVE_CONTACT_ERROR';

export const DELETE_CONTACT_START = 'DELETE_CONTACT_START';
export const DELETE_CONTACT_SUCCESS = 'DELETE_CONTACT_SUCCESS';
export const DELETE_CONTACT_ERROR = 'DELETE_CONTACT_ERROR';

export const QUICK_VIEW_CHANGE = 'CONTACT_QUICK_VIEW_CHANGE';
