export const SINGLE_SERVICE_VIEW_START = 'SINGLE_SERVICE_VIEW_START';
export const SINGLE_SERVICE_VIEW_SUCCESS = 'SINGLE_SERVICE_VIEW_SUCCESS';
export const SINGLE_SERVICE_VIEW_ERROR = 'SINGLE_SERVICE_VIEW_ERROR';

export const SAVE_SERVICE_VIEW_START = 'SAVE_SERVICE_VIEW_START';
export const SAVE_SERVICE_VIEW_SUCCESS = 'SAVE_SERVICE_VIEW_SUCCESS';
export const SAVE_SERVICE_VIEW_ERROR = 'SAVE_SERVICE_VIEW_ERROR';
