export const FETCH_TRACKS_START = 'FETCH_TRACKS_START';
export const FETCH_TRACKS_RESULTS = 'FETCH_TRACKS_RESULTS';
export const FETCH_TRACKS_ERROR = 'FETCH_TRACKS_ERROR';

export const MOVE_TRACKS_START = 'MOVE_TRACKS_START';
export const MOVE_TRACKS_RESULTS = 'MOVE_TRACKS_RESULTS';
export const MOVE_TRACKS_ERROR = 'MOVE_TRACKS_ERROR';

export const SINGLE_TRACKS_START = 'SINGLE_TRACKS_START';
export const SINGLE_TRACKS_RESULTS = 'SINGLE_TRACKS_RESULTS';
export const SINGLE_TRACKS_ERROR = 'SINGLE_TRACKS_ERROR';

export const SAVE_TRACKS_START = 'SAVE_TRACKS_START';
export const SAVE_TRACKS_SUCCESS = 'SAVE_TRACKS_SUCCESS';
export const SAVE_TRACKS_ERROR = 'SAVE_TRACKS_ERROR';

export const DELETE_TRACKS_START = 'DELETE_TRACKS_START';
export const DELETE_TRACKS_SUCCESS = 'DELETE_TRACKS_SUCCESS';
export const DELETE_TRACKS_ERROR = 'DELETE_TRACKS_ERROR';


