export const FETCH_FILTERED_TASK_START = 'FETCH_FILTERED_TASK_START';
export const FETCH_FILTERED_TASK_RESULTS = 'FETCH_FILTERED_TASK_RESULTS';
export const FETCH_FILTERED_TASK_ERROR = 'FETCH_FILTERED_TASK_ERROR';
export const FETCH_FILTERED_TASK_NEW_PAGE = 'FETCH_FILTERED_TASK_NEW_PAGE';
