export const SEARCH_CALENDAR_START = 'SEARCH_CALENDAR_START';
export const SEARCH_CALENDAR_RESULTS = 'SEARCH_CALENDAR_RESULTS';
export const SEARCH_CALENDAR_ERROR = 'SEARCH_CALENDAR_ERROR';

export const FETCH_CALENDAR_START = 'FETCH_CALENDAR_START';
export const FETCH_CALENDAR_RESULTS = 'FETCH_CALENDAR_RESULTS';
export const FETCH_CALENDAR_ERROR = 'FETCH_CALENDAR_ERROR';
export const FETCH_CALENDAR_NEW_PAGE = 'FETCH_CALENDAR_NEW_PAGE';
