export const SINGLE_EVENT_RATE_START = 'SINGLE_EVENT_RATE_START';
export const SINGLE_EVENT_RATE_SUCCESS = 'SINGLE_EVENT_RATE_SUCCESS';
export const SINGLE_EVENT_RATE_ERROR = 'SINGLE_EVENT_RATE_ERROR';

export const SAVE_EVENT_RATE_START = 'SAVE_EVENT_RATE_START';
export const SAVE_EVENT_RATE_SUCCESS = 'SAVE_EVENT_RATE_SUCCESS';
export const SAVE_EVENT_RATE_ERROR = 'SAVE_EVENT_RATE_ERROR';
