export const SINGLE_EVENT_START = 'SINGLE_EVENT_START';
export const SINGLE_EVENT_SUCCESS = 'SINGLE_EVENT_SUCCESS';
export const SINGLE_EVENT_ERROR = 'SINGLE_EVENT_ERROR';

export const SAVE_EVENT_START = 'SAVE_EVENT_START';
export const SAVE_EVENT_SUCCESS = 'SAVE_EVENT_SUCCESS';
export const SAVE_EVENT_ERROR = 'SAVE_EVENT_ERROR';
