export const SINGLE_TASK_START = 'SINGLE_TASK_START';
export const SINGLE_TASK_RESULTS = 'SINGLE_TASK_RESULTS';
export const SINGLE_TASK_ERROR = 'SINGLE_TASK_ERROR';

export const SAVE_TASK_START = 'SAVE_TASK_START';
export const SAVE_TASK_SUCCESS = 'SAVE_TASK_SUCCESS';
export const SAVE_TASK_ERROR = 'SAVE_TASK_ERROR';
