export const FETCH_CASE_DETAILS_START = 'FETCH_CASE_DETAILS_START';
export const FETCH_CASE_DETAILS_ERROR = 'FETCH_CASE_DETAILS_ERROR';
export const FETCH_CASE_DETAILS_RESULTS = 'FETCH_CASE_DETAILS_RESULTS';

export const CASE_REQUEST_DELETE = 'CASE_REQUEST_DELETE';
export const CASE_DELETE_START = 'CASE_DELETE_START';
export const CASE_DELETE_SUCCESS = 'CASE_DELETE_SUCCESS';
export const CASE_DELETE_ERROR = 'CASE_DELETE_ERROR';

export const SERVICE_REQUEST_DELETE = 'SERVICE_REQUEST_DELETE';
export const SERVICE_DELETE_START = 'SERVICE_DELETE_START';
export const SERVICE_DELETE_SUCCESS = 'SERVICE_DELETE_SUCCESS';
export const SERVICE_DELETE_ERROR = 'SERVICE_DELETE_ERROR';

export const REQUEST_DELETE_OPEN_MODAL = 'REQUEST_DELETE_OPEN_MODAL';
export const REQUEST_DELETE_CLOSE_MODAL = 'REQUEST_DELETE_CLOSE_MODAL';

export const SERVICE_REASON_START = 'SERVICE_REASON_START';
export const SERVICE_REASON_SUCCESS = 'SERVICE_REASON_SUCCESS';
export const SERVICE_REASON_ERROR = 'SERVICE_REASON_ERROR';
export const SERVICE_REASON_OPEN_DRAWER = 'SERVICE_REASON_OPEN_DRAWER';
export const SERVICE_RESTORE_START = 'SERVICE_RESTORE_START';
