export const RESET_CLIENT_UPDATE_DATA = 'RESET_CLIENT_UPDATE_DATA';

export const SEARCH_CLIENT_UPDATE_START = 'SEARCH_CLIENT_UPDATE_START';

export const FETCH_CLIENT_UPDATE_START = 'FETCH_CLIENT_UPDATE_START';
export const FETCH_CLIENT_UPDATE_SUCCESS = 'FETCH_CLIENT_UPDATE_SUCCESS';
export const FETCH_CLIENT_UPDATE_ERROR = 'FETCH_CLIENT_UPDATE_ERROR';
export const FETCH_CLIENT_UPDATE_NEW_PAGE = 'FETCH_CLIENT_UPDATE_NEW_PAGE';

export const SAVE_CLIENT_UPDATE_START = 'SAVE_CLIENT_UPDATE_START';
export const SAVE_CLIENT_UPDATE_ERROR = 'SAVE_CLIENT_UPDATE_ERROR';
export const SAVE_CLIENT_UPDATE_SUCCESS = 'SAVE_CLIENT_UPDATE_SUCCESS';
