export const SINGLE_SERVICE_START = 'SINGLE_SERVICE_START';
export const SINGLE_SERVICE_RESULTS = 'SINGLE_SERVICE_RESULTS';
export const SINGLE_SERVICE_ERROR = 'SINGLE_SERVICE_ERROR';

export const SAVE_SERVICE_START = 'SAVE_SERVICE_START';
export const SAVE_SERVICE_SUCCESS = 'SAVE_SERVICE_SUCCESS';
export const SAVE_SERVICE_ERROR = 'SAVE_SERVICE_ERROR';

export const GO_TO_STEP = 'GO_TO_STEP';
