export const STATUS_CLIENT_UPDATES_START = 'STATUS_CLIENT_UPDATES_START';
export const STATUS_CLIENT_UPDATES_ERROR = 'STATUS_CLIENT_UPDATES_ERROR';
export const STATUS_CLIENT_UPDATES_SUCCESS = 'STATUS_CLIENT_UPDATES_SUCCESS';
