export const FETCH_SINGLE_VENUE_START = 'FETCH_SINGLE_VENUE_START';
export const FETCH_SINGLE_VENUE_ERROR = 'FETCH_SINGLE_VENUE_ERROR';
export const FETCH_SINGLE_VENUE_SUCCESS = 'FETCH_SINGLE_VENUE_SUCCESS';

export const FETCH_JUDGE_NEW_PAGE = 'FETCH_JUDGE_NEW_PAGE';
export const FETCH_JUDGE_START = 'FETCH_JUDGE_START';
export const FETCH_JUDGE_SUCCESS = 'FETCH_JUDGE_SUCCESS';
export const FETCH_JUDGE_ERROR = 'FETCH_JUDGE_ERROR';
export const SEARCH_JUDGE_START = 'SEARCH_JUDGE_START';
export const SINGLE_JUDGE_START = 'SINGLE_JUDGE_START';
export const RESET_JUDGE_DATA = 'RESET_JUDGE_DATA';

export const VENUE_OVERVIEW_START = 'VENUE_OVERVIEW_START';
export const VENUE_OVERVIEW_ERROR = 'VENUE_OVERVIEW_ERROR';
export const VENUE_OVERVIEW_SUCCESS = 'VENUE_OVERVIEW_SUCCESS';
