export const SEARCH_USER_START = 'SEARCH_USER_START';
export const SEARCH_USER_RESULTS = 'SEARCH_USER_RESULTS';
export const SEARCH_USER_ERROR = 'SEARCH_USER_ERROR';

export const FETCH_USER_START = 'FETCH_USER_START';
export const FETCH_USER_RESULTS = 'FETCH_USER_RESULTS';
export const FETCH_USER_ERROR = 'FETCH_USER_ERROR';

export const SINGLE_USER_START = 'SINGLE_USER_START';
export const SINGLE_USER_RESULTS = 'SINGLE_USER_RESULTS';
export const SINGLE_USER_ERROR = 'SINGLE_USER_ERROR';

export const SAVE_USER_START = 'SAVE_USER_START';
export const SAVE_USER_SUCCESS = 'SAVE_USER_SUCCESS';
export const SAVE_USER_ERROR = 'SAVE_USER_ERROR';

export const DELETE_USER_START = 'DELETE_USER_START';
export const DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS';
export const DELETE_USER_ERROR = 'DELETE_USER_ERROR';

export const SWITCH_USER_STATUS_START = 'SWITCH_USER_STATUS_START';
export const SWITCH_USER_STATUS_SUCCESS = 'SWITCH_USER_STATUS_SUCCESS';
export const SWITCH_USER_STATUS_ERROR = 'SWITCH_USER_STATUS_ERROR';
