export const FETCH_SINGLE_ORGANIZATION_START = 'FETCH_SINGLE_ORGANIZATION_START';
export const FETCH_SINGLE_ORGANIZATION_ERROR = 'FETCH_SINGLE_ORGANIZATION_ERROR';
export const FETCH_SINGLE_ORGANIZATION_SUCCESS = 'FETCH_SINGLE_ORGANIZATION_SUCCESS';

export const ORGANIZATION_GENERATE_LIEN_REPORT_START = 'ORGANIZATION_GENERATE_LIEN_REPORT_START';
export const ORGANIZATION_GENERATE_LIEN_REPORT_SUCCESS = 'ORGANIZATION_GENERATE_LIEN_REPORT_SUCCESS';
export const ORGANIZATION_GENERATE_LIEN_REPORT_ERROR = 'ORGANIZATION_GENERATE_LIEN_REPORT_ERROR';

export const ORGANIZATION_OVERVIEW_START = 'ORGANIZATION_OVERVIEW_START';
export const ORGANIZATION_OVERVIEW_ERROR = 'ORGANIZATION_OVERVIEW_ERROR';
export const ORGANIZATION_OVERVIEW_SUCCESS = 'ORGANIZATION_OVERVIEW_SUCCESS';
