export const SINGLE_ORGANIZATION_FORM_TYPE_CHANGE = 'SINGLE_ORGANIZATION_FORM_TYPE_CHANGE';

export const SEARCH_ORGANIZATION_START = 'SEARCH_ORGANIZATION_START';
export const SEARCH_ORGANIZATION_RESULTS = 'SEARCH_ORGANIZATION_RESULTS';
export const SEARCH_ORGANIZATION_ERROR = 'SEARCH_ORGANIZATION_ERROR';

export const FETCH_ORGANIZATION_START = 'FETCH_ORGANIZATION_START';
export const FETCH_ORGANIZATION_RESULTS = 'FETCH_ORGANIZATION_RESULTS';
export const FETCH_ORGANIZATION_ERROR = 'FETCH_ORGANIZATION_ERROR';
export const FETCH_ORGANIZATION_NEW_PAGE = 'FETCH_ORGANIZATION_NEW_PAGE';

export const SINGLE_ORGANIZATION_START = 'SINGLE_ORGANIZATION_START';
export const SINGLE_ORGANIZATION_RESULTS = 'SINGLE_ORGANIZATION_RESULTS';
export const SINGLE_ORGANIZATION_ERROR = 'SINGLE_ORGANIZATION_ERROR';

export const SAVE_ORGANIZATION_START = 'SAVE_ORGANIZATION_START';
export const SAVE_ORGANIZATION_SUCCESS = 'SAVE_ORGANIZATION_SUCCESS';
export const SAVE_ORGANIZATION_ERROR = 'SAVE_ORGANIZATION_ERROR';

export const DELETE_ORGANIZATION_START = 'DELETE_ORGANIZATION_START';
export const DELETE_ORGANIZATION_SUCCESS = 'DELETE_ORGANIZATION_SUCCESS';
export const DELETE_ORGANIZATION_ERROR = 'DELETE_ORGANIZATION_ERROR';
