export const RESET_CASE_DATA = 'RESET_CASE_DATA';

export const SEARCH_CASE_START = 'SEARCH_CASE_START';

export const FETCH_CASE_START = 'FETCH_CASE_START';
export const FETCH_CASE_SUCCESS = 'FETCH_CASE_SUCCESS';
export const FETCH_CASE_ERROR = 'FETCH_CASE_ERROR';
export const FETCH_CASE_NEW_PAGE = 'FETCH_CASE_NEW_PAGE';

export const SINGLE_CASE_START = 'SINGLE_CASE_START';
export const SINGLE_CASE_SUCCESS = 'SINGLE_CASE_SUCCESS';
export const SINGLE_CASE_ERROR = 'SINGLE_CASE_ERROR';

export const SAVE_CASE_START = 'SAVE_CASE_START';
export const SAVE_CASE_SUCCESS = 'SAVE_CASE_SUCCESS';
export const SAVE_CASE_ERROR = 'SAVE_CASE_ERROR';

export const DELETE_CASE_START = 'DELETE_CASE_START';
export const DELETE_CASE_SUCCESS = 'DELETE_CASE_SUCCESS';
export const DELETE_CASE_ERROR = 'DELETE_CASE_ERROR';

export const QUICK_VIEW_CHANGE = 'QUICK_VIEW_CHANGE';
